/**
 * Полный реестр WB OpenAPI (~309 ops) из официальных YAML-спеков.
 * Автоген из /tmp/wb-openapi/*.yaml — не править руками.
 * Generated: 2026-08-14T12:13:24.201263+00:00
 */

import { WB_HOSTS, type WbHttpResult } from './agent-wb-openapi-client.ts';

export type WbEndpoint = {
  id: string;
  file: string;
  method: string;
  path: string;
  summary: string;
  readonly: boolean;
  hostKey: keyof typeof WB_HOSTS;
};

/** Host for WB Digital (не в дневном WB_HOSTS). */
export const WB_OPENAPI_ENDPOINTS: WbEndpoint[] = [
  { id: "getPing", file: "01-general.yaml", method: "GET", path: "/ping", summary: "Проверка подключения", readonly: true, hostKey: "common" },
  { id: "getV2News", file: "01-general.yaml", method: "GET", path: "/api/communications/v2/news", summary: "Получение новостей портала продавцов", readonly: true, hostKey: "common" },
  { id: "getV1SellerInfo", file: "01-general.yaml", method: "GET", path: "/api/v1/seller-info", summary: "Получить информацию о продавце", readonly: true, hostKey: "common" },
  { id: "getV1Rating", file: "01-general.yaml", method: "GET", path: "/api/common/v1/rating", summary: "Получить рейтинг продавца", readonly: true, hostKey: "feedbacks" },
  { id: "getV1Subscriptions", file: "01-general.yaml", method: "GET", path: "/api/common/v1/subscriptions", summary: "Получить информацию о подписке Джем", readonly: true, hostKey: "common" },
  { id: "getV1TariffConstructorOptions", file: "01-general.yaml", method: "GET", path: "/api/common/v1/tariff-constructor/options", summary: "Получить информацию об опциях Конструктора тарифов", readonly: true, hostKey: "common" },
  { id: "postV1Invite", file: "01-general.yaml", method: "POST", path: "/api/v1/invite", summary: "Создать приглашение для нового пользователя", readonly: false, hostKey: "users" },
  { id: "getV1Users", file: "01-general.yaml", method: "GET", path: "/api/v1/users", summary: "Получить список активных или приглашённых пользователей продавца", readonly: true, hostKey: "users" },
  { id: "putV1UsersAccess", file: "01-general.yaml", method: "PUT", path: "/api/v1/users/access", summary: "Изменить права доступа пользователей", readonly: false, hostKey: "users" },
  { id: "deleteV1User", file: "01-general.yaml", method: "DELETE", path: "/api/v1/user", summary: "Удалить пользователя", readonly: false, hostKey: "users" },
  { id: "get_content_v2_object_parent_all", file: "02-products.yaml", method: "GET", path: "/content/v2/object/parent/all", summary: "Родительские категории товаров", readonly: true, hostKey: "content" },
  { id: "get_content_v2_object_all", file: "02-products.yaml", method: "GET", path: "/content/v2/object/all", summary: "Список предметов", readonly: true, hostKey: "content" },
  { id: "get_content_v2_object_charcs_subjectId", file: "02-products.yaml", method: "GET", path: "/content/v2/object/charcs/{subjectId}", summary: "Характеристики предмета", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_colors", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/colors", summary: "Цвет", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_kinds", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/kinds", summary: "Пол", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_countries", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/countries", summary: "Страна производства", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_seasons", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/seasons", summary: "Сезон", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_vat", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/vat", summary: "Ставка НДС", readonly: true, hostKey: "content" },
  { id: "get_content_v2_directory_tnved", file: "02-products.yaml", method: "GET", path: "/content/v2/directory/tnved", summary: "ТНВЭД-код", readonly: true, hostKey: "content" },
  { id: "get_api_content_v1_brands", file: "02-products.yaml", method: "GET", path: "/api/content/v1/brands", summary: "Бренды", readonly: true, hostKey: "content" },
  { id: "get_content_v2_tags", file: "02-products.yaml", method: "GET", path: "/content/v2/tags", summary: "Список ярлыков", readonly: true, hostKey: "content" },
  { id: "post_content_v2_tag", file: "02-products.yaml", method: "POST", path: "/content/v2/tag", summary: "Создание ярлыка", readonly: false, hostKey: "content" },
  { id: "patch_content_v2_tag_id", file: "02-products.yaml", method: "PATCH", path: "/content/v2/tag/{id}", summary: "Изменение ярлыка", readonly: false, hostKey: "content" },
  { id: "delete_content_v2_tag_id", file: "02-products.yaml", method: "DELETE", path: "/content/v2/tag/{id}", summary: "Удаление ярлыка", readonly: false, hostKey: "content" },
  { id: "post_content_v2_tag_nomenclature_link", file: "02-products.yaml", method: "POST", path: "/content/v2/tag/nomenclature/link", summary: "Управление ярлыками в карточке товара", readonly: false, hostKey: "content" },
  { id: "post_content_v2_get_cards_list", file: "02-products.yaml", method: "POST", path: "/content/v2/get/cards/list", summary: "Список карточек товаров", readonly: true, hostKey: "content" },
  { id: "post_content_v2_cards_error_list", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/error/list", summary: "Список несозданных карточек товаров с ошибками", readonly: true, hostKey: "content" },
  { id: "post_content_v2_cards_update", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/update", summary: "Редактирование карточек товаров", readonly: false, hostKey: "content" },
  { id: "post_content_v2_cards_moveNm", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/moveNm", summary: "Объединение и разъединение карточек товаров", readonly: false, hostKey: "content" },
  { id: "post_content_v2_cards_delete_trash", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/delete/trash", summary: "Перенос карточек товаров в корзину", readonly: false, hostKey: "content" },
  { id: "post_content_v2_cards_recover", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/recover", summary: "Восстановление карточек товаров из корзины", readonly: false, hostKey: "content" },
  { id: "post_content_v2_get_cards_trash", file: "02-products.yaml", method: "POST", path: "/content/v2/get/cards/trash", summary: "Список карточек товаров в корзине", readonly: true, hostKey: "content" },
  { id: "get_content_v2_cards_limits", file: "02-products.yaml", method: "GET", path: "/content/v2/cards/limits", summary: "Лимиты карточек товаров", readonly: true, hostKey: "content" },
  { id: "post_content_v2_barcodes", file: "02-products.yaml", method: "POST", path: "/content/v2/barcodes", summary: "Генерация баркодов", readonly: false, hostKey: "content" },
  { id: "post_content_v2_cards_upload", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/upload", summary: "Создание карточек товаров", readonly: false, hostKey: "content" },
  { id: "post_content_v2_cards_upload_add", file: "02-products.yaml", method: "POST", path: "/content/v2/cards/upload/add", summary: "Создание карточек товаров с присоединением", readonly: false, hostKey: "content" },
  { id: "post_content_v3_media_file", file: "02-products.yaml", method: "POST", path: "/content/v3/media/file", summary: "Загрузить медиафайл", readonly: false, hostKey: "content" },
  { id: "post_content_v3_media_save", file: "02-products.yaml", method: "POST", path: "/content/v3/media/save", summary: "Загрузить медиафайлы по ссылкам", readonly: false, hostKey: "content" },
  { id: "postV1RecommendationsList", file: "02-products.yaml", method: "POST", path: "/api/content/v1/recommendations/list", summary: "Список рекомендаций в карточках товаров", readonly: true, hostKey: "content" },
  { id: "postV1RecommendationsSet", file: "02-products.yaml", method: "POST", path: "/api/content/v1/recommendations/set", summary: "Установить рекомендации для товаров", readonly: false, hostKey: "content" },
  { id: "post_api_v2_upload_task", file: "02-products.yaml", method: "POST", path: "/api/v2/upload/task", summary: "Установить цены и скидки", readonly: false, hostKey: "prices" },
  { id: "post_api_v2_upload_task_size", file: "02-products.yaml", method: "POST", path: "/api/v2/upload/task/size", summary: "Установить цены для размеров", readonly: false, hostKey: "prices" },
  { id: "post_api_v2_upload_task_club_discount", file: "02-products.yaml", method: "POST", path: "/api/v2/upload/task/club-discount", summary: "Установить скидки WB Клуба", readonly: false, hostKey: "prices" },
  { id: "postV1UploadTaskB2bWholesale", file: "02-products.yaml", method: "POST", path: "/api/discounts-prices/v1/upload/task/b2b/wholesale", summary: "Установить оптовые скидки для B2B-продаж", readonly: false, hostKey: "prices" },
  { id: "get_api_v2_history_tasks", file: "02-products.yaml", method: "GET", path: "/api/v2/history/tasks", summary: "Состояние обработанной загрузки", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_history_goods_task", file: "02-products.yaml", method: "GET", path: "/api/v2/history/goods/task", summary: "Детализация обработанной загрузки", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_buffer_tasks", file: "02-products.yaml", method: "GET", path: "/api/v2/buffer/tasks", summary: "Состояние необработанной загрузки", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_buffer_goods_task", file: "02-products.yaml", method: "GET", path: "/api/v2/buffer/goods/task", summary: "Детализация необработанной загрузки", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_list_goods_filter", file: "02-products.yaml", method: "GET", path: "/api/v2/list/goods/filter", summary: "Получить товары с ценами", readonly: true, hostKey: "prices" },
  { id: "post_api_v2_list_goods_filter", file: "02-products.yaml", method: "POST", path: "/api/v2/list/goods/filter", summary: "Получить товары с ценами по артикулам", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_list_goods_size_nm", file: "02-products.yaml", method: "GET", path: "/api/v2/list/goods/size/nm", summary: "Получить размеры товара с ценами", readonly: true, hostKey: "prices" },
  { id: "get_api_v2_quarantine_goods", file: "02-products.yaml", method: "GET", path: "/api/v2/quarantine/goods", summary: "Получить товары в карантине", readonly: true, hostKey: "prices" },
  { id: "put_api_v3_stocks_warehouseId", file: "02-products.yaml", method: "PUT", path: "/api/v3/stocks/{warehouseId}", summary: "Обновить остатки товаров", readonly: false, hostKey: "marketplace" },
  { id: "delete_api_v3_stocks_warehouseId", file: "02-products.yaml", method: "DELETE", path: "/api/v3/stocks/{warehouseId}", summary: "Удалить остатки товаров", readonly: false, hostKey: "marketplace" },
  { id: "post_api_v3_stocks_warehouseId", file: "02-products.yaml", method: "POST", path: "/api/v3/stocks/{warehouseId}", summary: "Получить остатки товаров", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_offices", file: "02-products.yaml", method: "GET", path: "/api/v3/offices", summary: "Получить список складов WB", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_warehouses", file: "02-products.yaml", method: "GET", path: "/api/v3/warehouses", summary: "Получить список складов продавца", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_warehouses", file: "02-products.yaml", method: "POST", path: "/api/v3/warehouses", summary: "Создать склад продавца", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_warehouses_warehouseId", file: "02-products.yaml", method: "PUT", path: "/api/v3/warehouses/{warehouseId}", summary: "Обновить склад продавца", readonly: false, hostKey: "marketplace" },
  { id: "delete_api_v3_warehouses_warehouseId", file: "02-products.yaml", method: "DELETE", path: "/api/v3/warehouses/{warehouseId}", summary: "Удалить склад продавца", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_dbw_warehouses_warehouseId_contacts", file: "02-products.yaml", method: "GET", path: "/api/v3/dbw/warehouses/{warehouseId}/contacts", summary: "Список контактов", readonly: true, hostKey: "marketplace" },
  { id: "put_api_v3_dbw_warehouses_warehouseId_contacts", file: "02-products.yaml", method: "PUT", path: "/api/v3/dbw/warehouses/{warehouseId}/contacts", summary: "Обновить список контактов", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_passes_offices", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/passes/offices", summary: "Получить список складов, для которых требуется пропуск", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_passes", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/passes", summary: "Получить список пропусков", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_passes", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/passes", summary: "Создать пропуск", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_passes_passId", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/passes/{passId}", summary: "Обновить пропуск", readonly: false, hostKey: "marketplace" },
  { id: "delete_api_v3_passes_passId", file: "03-orders-fbs.yaml", method: "DELETE", path: "/api/v3/passes/{passId}", summary: "Удалить пропуск", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_orders_new", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/orders/new", summary: "Получить список новых сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_orders", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/orders", summary: "Получить информацию о сборочных заданиях", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_orders_status", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/orders/status", summary: "Получить статусы сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_supplies_orders_reshipment", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/supplies/orders/reshipment", summary: "Получить все сборочные задания для повторной отгрузки", readonly: true, hostKey: "marketplace" },
  { id: "patch_api_v3_orders_orderId_cancel", file: "03-orders-fbs.yaml", method: "PATCH", path: "/api/v3/orders/{orderId}/cancel", summary: "Отменить сборочное задание", readonly: false, hostKey: "marketplace" },
  { id: "post_api_v3_orders_stickers", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/orders/stickers", summary: "Получить стикеры сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "post_api_marketplace_v3_orders_meta", file: "03-orders-fbs.yaml", method: "POST", path: "/api/marketplace/v3/orders/meta", summary: "Получить идентификаторы маркировки сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "delete_api_v3_orders_orderId_meta", file: "03-orders-fbs.yaml", method: "DELETE", path: "/api/v3/orders/{orderId}/meta", summary: "Удалить идентификаторы маркировки сборочного задания", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_orders_orderId_meta_sgtin", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/orders/{orderId}/meta/sgtin", summary: "Закрепить код маркировки Честного знака за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_orders_orderId_meta_uin", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/orders/{orderId}/meta/uin", summary: "Закрепить УИН за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_orders_orderId_meta_imei", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/orders/{orderId}/meta/imei", summary: "Закрепить IMEI за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_orders_orderId_meta_gtin", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/orders/{orderId}/meta/gtin", summary: "Закрепить GTIN за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "put_api_v3_orders_orderId_meta_expiration", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/v3/orders/{orderId}/meta/expiration", summary: "Закрепить за сборочным заданием срок годности товара", readonly: false, hostKey: "marketplace" },
  { id: "put_api_marketplace_v3_orders_orderId_meta_customs_declaration", file: "03-orders-fbs.yaml", method: "PUT", path: "/api/marketplace/v3/orders/{orderId}/meta/customs-declaration", summary: "Закрепить номер ДТ за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "post_api_v3_orders_stickers_cross_border", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/orders/stickers/cross-border", summary: "Получить стикеры сборочных заданий трансграничных поставок", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_orders_status_history", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/orders/status/history", summary: "История статусов для сборочных заданий трансграничных поставок", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_orders_client", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/orders/client", summary: "Заказы с информацией по клиенту", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_supplies", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/supplies", summary: "Создать новую поставку", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_supplies", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/supplies", summary: "Получить список поставок", readonly: true, hostKey: "marketplace" },
  { id: "patch_api_marketplace_v3_supplies_supplyId_orders", file: "03-orders-fbs.yaml", method: "PATCH", path: "/api/marketplace/v3/supplies/{supplyId}/orders", summary: "Добавить сборочные задания к поставке", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_supplies_supplyId", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/supplies/{supplyId}", summary: "Получить информацию о поставке", readonly: true, hostKey: "marketplace" },
  { id: "delete_api_v3_supplies_supplyId", file: "03-orders-fbs.yaml", method: "DELETE", path: "/api/v3/supplies/{supplyId}", summary: "Удалить поставку", readonly: false, hostKey: "marketplace" },
  { id: "get_api_marketplace_v3_supplies_supplyId_order_ids", file: "03-orders-fbs.yaml", method: "GET", path: "/api/marketplace/v3/supplies/{supplyId}/order-ids", summary: "Получить ID сборочных заданий поставки", readonly: true, hostKey: "marketplace" },
  { id: "patch_api_v3_supplies_supplyId_deliver", file: "03-orders-fbs.yaml", method: "PATCH", path: "/api/v3/supplies/{supplyId}/deliver", summary: "Передать поставку в доставку", readonly: false, hostKey: "marketplace" },
  { id: "get_api_v3_supplies_supplyId_barcode", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/supplies/{supplyId}/barcode", summary: "Получить QR-код поставки", readonly: true, hostKey: "marketplace" },
  { id: "get_api_v3_supplies_supplyId_trbx", file: "03-orders-fbs.yaml", method: "GET", path: "/api/v3/supplies/{supplyId}/trbx", summary: "Получить список грузомест поставки", readonly: true, hostKey: "marketplace" },
  { id: "post_api_v3_supplies_supplyId_trbx", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/supplies/{supplyId}/trbx", summary: "Добавить грузоместа к поставке", readonly: false, hostKey: "marketplace" },
  { id: "delete_api_v3_supplies_supplyId_trbx", file: "03-orders-fbs.yaml", method: "DELETE", path: "/api/v3/supplies/{supplyId}/trbx", summary: "Удалить грузоместа из поставки", readonly: false, hostKey: "marketplace" },
  { id: "post_api_v3_supplies_supplyId_trbx_stickers", file: "03-orders-fbs.yaml", method: "POST", path: "/api/v3/supplies/{supplyId}/trbx/stickers", summary: "Получить стикеры грузомест поставки", readonly: true, hostKey: "marketplace" },
  { id: "get_api_marketplace_v3_fbs_orders_archive", file: "03-orders-fbs.yaml", method: "GET", path: "/api/marketplace/v3/fbs/orders/archive", summary: "Получить список архивных сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "getMarketplaceV3FbsSettingsAutoreturns", file: "03-orders-fbs.yaml", method: "GET", path: "/api/marketplace/v3/fbs/settings/autoreturns", summary: "Получить настройки автовозврата продавца", readonly: true, hostKey: "marketplace" },
  { id: "patchMarketplaceV3FbsSettingsAutoreturns", file: "03-orders-fbs.yaml", method: "PATCH", path: "/api/marketplace/v3/fbs/settings/autoreturns", summary: "Обновить настройки автовозврата продавца", readonly: false, hostKey: "marketplace" },
  { id: "postMarketplaceV3FbsSettingsAutoreturnsItems", file: "03-orders-fbs.yaml", method: "POST", path: "/api/marketplace/v3/fbs/settings/autoreturns/items", summary: "Получить настройки автовозврата товаров", readonly: true, hostKey: "marketplace" },
  { id: "patchMarketplaceV3FbsSettingsAutoreturnsItems", file: "03-orders-fbs.yaml", method: "PATCH", path: "/api/marketplace/v3/fbs/settings/autoreturns/items", summary: "Обновить настройки автовозврата товаров", readonly: false, hostKey: "marketplace" },
  { id: "getMarketplaceV3FbsSettingsAutoreturnsSubcategoriesRestricted", file: "03-orders-fbs.yaml", method: "GET", path: "/api/marketplace/v3/fbs/settings/autoreturns/subcategories/restricted", summary: "Получить предметы, которые не хранятся на складах WB", readonly: true, hostKey: "marketplace" },
  { id: "getV3DbwOrdersNew", file: "04-orders-dbw.yaml", method: "GET", path: "/api/v3/dbw/orders/new", summary: "Получить список новых сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "getV3DbwOrders", file: "04-orders-dbw.yaml", method: "GET", path: "/api/v3/dbw/orders", summary: "Получить информацию о завершенных сборочных заданиях", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbwOrdersDeliveryDate", file: "04-orders-dbw.yaml", method: "POST", path: "/api/v3/dbw/orders/delivery-date", summary: "Получить дату и время доставки", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbwOrdersClient", file: "04-orders-dbw.yaml", method: "POST", path: "/api/marketplace/v3/dbw/orders/client", summary: "Информация о покупателе", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbwOrdersStatus", file: "04-orders-dbw.yaml", method: "POST", path: "/api/v3/dbw/orders/status", summary: "Получить статусы сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "patchV3DbwOrdersOrderIdConfirm", file: "04-orders-dbw.yaml", method: "PATCH", path: "/api/v3/dbw/orders/{orderId}/confirm", summary: "Перевести на сборку", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbwOrdersStickers", file: "04-orders-dbw.yaml", method: "POST", path: "/api/v3/dbw/orders/stickers", summary: "Получить стикеры сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbwOrdersStatusDeliver", file: "04-orders-dbw.yaml", method: "POST", path: "/api/marketplace/v3/dbw/orders/status/deliver", summary: "Перевести сборочные задания в доставку", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbwOrdersCourier", file: "04-orders-dbw.yaml", method: "POST", path: "/api/v3/dbw/orders/courier", summary: "Информация о курьере", readonly: true, hostKey: "marketplace" },
  { id: "patchV3DbwOrdersOrderIdCancel", file: "04-orders-dbw.yaml", method: "PATCH", path: "/api/v3/dbw/orders/{orderId}/cancel", summary: "Отменить сборочное задание", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbwOrdersMetaDetails", file: "04-orders-dbw.yaml", method: "POST", path: "/api/marketplace/v3/dbw/orders/meta/details", summary: "Получить идентификаторы маркировки сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbwOrdersMetaDelete", file: "04-orders-dbw.yaml", method: "POST", path: "/api/marketplace/v3/dbw/orders/meta/delete", summary: "Удалить идентификаторы маркировки сборочных заданий", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbwOrdersMetaSgtin", file: "04-orders-dbw.yaml", method: "POST", path: "/api/marketplace/v3/dbw/orders/meta/sgtin", summary: "Закрепить коды маркировки Честного знака за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "putV3DbwOrdersOrderIdMetaUin", file: "04-orders-dbw.yaml", method: "PUT", path: "/api/v3/dbw/orders/{orderId}/meta/uin", summary: "Закрепить УИН за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "putV3DbwOrdersOrderIdMetaImei", file: "04-orders-dbw.yaml", method: "PUT", path: "/api/v3/dbw/orders/{orderId}/meta/imei", summary: "Закрепить IMEI за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "putV3DbwOrdersOrderIdMetaGtin", file: "04-orders-dbw.yaml", method: "PUT", path: "/api/v3/dbw/orders/{orderId}/meta/gtin", summary: "Закрепить GTIN за сборочным заданием", readonly: false, hostKey: "marketplace" },
  { id: "getV3DbsOrdersNew", file: "05-orders-dbs.yaml", method: "GET", path: "/api/v3/dbs/orders/new", summary: "Получить список новых сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "getV3DbsOrders", file: "05-orders-dbs.yaml", method: "GET", path: "/api/v3/dbs/orders", summary: "Получить информацию о завершенных сборочных заданиях", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsGroupsInfo", file: "05-orders-dbs.yaml", method: "POST", path: "/api/v3/dbs/groups/info", summary: "Получить информацию о платной доставке", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersClient", file: "05-orders-dbs.yaml", method: "POST", path: "/api/v3/dbs/orders/client", summary: "Информация о покупателе", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersB2bInfo", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/b2b/info", summary: "Информация о покупателе B2B", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersDeliveryDate", file: "05-orders-dbs.yaml", method: "POST", path: "/api/v3/dbs/orders/delivery-date", summary: "Получить дату и время доставки", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusInfo", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/info", summary: "Получить статусы сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusCancel", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/cancel", summary: "Отменить сборочные задания", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusConfirm", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/confirm", summary: "Перевести сборочные задания на сборку", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStickers", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/stickers", summary: "Получить стикеры для сборочных заданий с доставкой в ПВЗ", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusDeliver", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/deliver", summary: "Перевести сборочные задания в доставку", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusReceive", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/receive", summary: "Сообщить о получении заказов", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersStatusReject", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/status/reject", summary: "Сообщить об отказе от заказов", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaDetails", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/details", summary: "Получить идентификаторы маркировки сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaDelete", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/delete", summary: "Удалить идентификаторы маркировки сборочных заданий", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaSgtin", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/sgtin", summary: "Закрепить коды маркировки Честного знака за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaUin", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/uin", summary: "Закрепить УИН за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaImei", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/imei", summary: "Закрепить IMEI за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaGtin", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/gtin", summary: "Закрепить GTIN за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3DbsOrdersMetaCustomsDeclaration", file: "05-orders-dbs.yaml", method: "POST", path: "/api/marketplace/v3/dbs/orders/meta/customs-declaration", summary: "Закрепить номера ДТ за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "getV3ClickCollectOrdersNew", file: "06-in-store-pickup.yaml", method: "GET", path: "/api/v3/click-collect/orders/new", summary: "Получить список новых сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "getV3ClickCollectOrders", file: "06-in-store-pickup.yaml", method: "GET", path: "/api/v3/click-collect/orders", summary: "Получить информацию о завершённых сборочных заданиях", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersFinalPrice", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/final-price", summary: "Получить цены продавца и суммы к оплате", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusConfirm", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/confirm", summary: "Перевести сборочные задания на сборку", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusPrepare", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/prepare", summary: "Сообщить, что сборочные задания готовы к выдаче", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersClient", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/v3/click-collect/orders/client", summary: "Информация о покупателе", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersClientIdentity", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/v3/click-collect/orders/client/identity", summary: "Проверить, что заказ принадлежит покупателю", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusReceive", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/receive", summary: "Сообщить, что заказы приняты покупателями", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusReject", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/reject", summary: "Сообщить об отказе от заказов", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusInfo", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/info", summary: "Получить статусы сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersStatusCancel", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/status/cancel", summary: "Отменить сборочные задания", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaDetails", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/details", summary: "Получить идентификаторы маркировки сборочных заданий", readonly: true, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaDelete", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/delete", summary: "Удалить идентификаторы маркировки сборочных заданий", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaSgtin", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/sgtin", summary: "Закрепить коды маркировки Честного знака за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaUin", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/uin", summary: "Закрепить УИН за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaImei", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/imei", summary: "Закрепить IMEI за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaGtin", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/gtin", summary: "Закрепить GTIN за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV3ClickCollectOrdersMetaCustomsDeclaration", file: "06-in-store-pickup.yaml", method: "POST", path: "/api/marketplace/v3/click-collect/orders/meta/customs-declaration", summary: "Закрепить номера ДТ за сборочными заданиями", readonly: false, hostKey: "marketplace" },
  { id: "postV1AcceptanceOptions", file: "07-orders-fbw.yaml", method: "POST", path: "/api/v1/acceptance/options", summary: "Опции приёмки", readonly: true, hostKey: "supplies" },
  { id: "getV1Warehouses", file: "07-orders-fbw.yaml", method: "GET", path: "/api/v1/warehouses", summary: "Список складов", readonly: true, hostKey: "supplies" },
  { id: "getV1TransitTariffs", file: "07-orders-fbw.yaml", method: "GET", path: "/api/v1/transit-tariffs", summary: "Транзитные направления", readonly: true, hostKey: "supplies" },
  { id: "postV1Supplies", file: "07-orders-fbw.yaml", method: "POST", path: "/api/v1/supplies", summary: "Список поставок", readonly: true, hostKey: "supplies" },
  { id: "getV1SuppliesId", file: "07-orders-fbw.yaml", method: "GET", path: "/api/v1/supplies/{ID}", summary: "Детали поставки", readonly: true, hostKey: "supplies" },
  { id: "getV1SuppliesIdGoods", file: "07-orders-fbw.yaml", method: "GET", path: "/api/v1/supplies/{ID}/goods", summary: "Товары поставки", readonly: true, hostKey: "supplies" },
  { id: "getV1SuppliesIdPackage", file: "07-orders-fbw.yaml", method: "GET", path: "/api/v1/supplies/{ID}/package", summary: "Упаковка поставки", readonly: true, hostKey: "supplies" },
  { id: "get_adv_v1_promotion_count", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/promotion/count", summary: "Списки кампаний", readonly: true, hostKey: "advert" },
  { id: "get_api_advert_v2_adverts", file: "08-promotion.yaml", method: "GET", path: "/api/advert/v2/adverts", summary: "Информация о кампаниях", readonly: true, hostKey: "advert" },
  { id: "post_api_advert_v1_bids_min", file: "08-promotion.yaml", method: "POST", path: "/api/advert/v1/bids/min", summary: "Минимальные ставки для карточек товаров", readonly: true, hostKey: "advert" },
  { id: "post_adv_v2_seacat_save_ad", file: "08-promotion.yaml", method: "POST", path: "/adv/v2/seacat/save-ad", summary: "Создать кампанию", readonly: false, hostKey: "advert" },
  { id: "get_adv_v1_supplier_subjects", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/supplier/subjects", summary: "Предметы для кампаний", readonly: true, hostKey: "advert" },
  { id: "post_adv_v2_supplier_nms", file: "08-promotion.yaml", method: "POST", path: "/adv/v2/supplier/nms", summary: "Карточки товаров для кампаний", readonly: true, hostKey: "advert" },
  { id: "get_adv_v0_delete", file: "08-promotion.yaml", method: "GET", path: "/adv/v0/delete", summary: "Удаление кампании", readonly: true, hostKey: "advert" },
  { id: "post_adv_v0_rename", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/rename", summary: "Переименование кампании", readonly: false, hostKey: "advert" },
  { id: "get_adv_v0_start", file: "08-promotion.yaml", method: "GET", path: "/adv/v0/start", summary: "Запуск кампании", readonly: true, hostKey: "advert" },
  { id: "get_adv_v0_pause", file: "08-promotion.yaml", method: "GET", path: "/adv/v0/pause", summary: "Пауза кампании", readonly: true, hostKey: "advert" },
  { id: "get_adv_v0_stop", file: "08-promotion.yaml", method: "GET", path: "/adv/v0/stop", summary: "Завершение кампании", readonly: true, hostKey: "advert" },
  { id: "put_adv_v0_auction_placements", file: "08-promotion.yaml", method: "PUT", path: "/adv/v0/auction/placements", summary: "Изменение мест размещения в кампаниях с ручной ставкой", readonly: false, hostKey: "advert" },
  { id: "patch_api_advert_v1_bids", file: "08-promotion.yaml", method: "PATCH", path: "/api/advert/v1/bids", summary: "Изменение ставок в кампаниях", readonly: false, hostKey: "advert" },
  { id: "get_adv_v1_balance", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/balance", summary: "Баланс", readonly: true, hostKey: "advert" },
  { id: "get_adv_v1_budget", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/budget", summary: "Бюджет кампании", readonly: true, hostKey: "advert" },
  { id: "post_adv_v1_budget_deposit", file: "08-promotion.yaml", method: "POST", path: "/adv/v1/budget/deposit", summary: "Пополнение бюджета кампании", readonly: false, hostKey: "advert" },
  { id: "get_adv_v1_upd", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/upd", summary: "Получение истории затрат", readonly: true, hostKey: "advert" },
  { id: "get_adv_v1_payments", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/payments", summary: "Получение истории пополнений счёта", readonly: true, hostKey: "advert" },
  { id: "patch_adv_v0_auction_nms", file: "08-promotion.yaml", method: "PATCH", path: "/adv/v0/auction/nms", summary: "Изменение списка карточек товаров в кампаниях", readonly: false, hostKey: "advert" },
  { id: "get_api_advert_v0_bids_recommendations", file: "08-promotion.yaml", method: "GET", path: "/api/advert/v0/bids/recommendations", summary: "Рекомендуемые ставки для карточек товаров и поисковых кластеров", readonly: true, hostKey: "advert" },
  { id: "post_adv_v0_normquery_stats", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/stats", summary: "Статистика поисковых кластеров", readonly: true, hostKey: "advert" },
  { id: "post_adv_v0_normquery_get_bids", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/get-bids", summary: "Список ставок поисковых кластеров", readonly: true, hostKey: "advert" },
  { id: "getV1Config", file: "08-promotion.yaml", method: "GET", path: "/api/advert/v1/config", summary: "Конфигурационные значения продвижения", readonly: true, hostKey: "advert" },
  { id: "postV1NormqueryBids", file: "08-promotion.yaml", method: "POST", path: "/api/advert/v1/normquery/bids", summary: "Установить ставки для поисковых кластеров в валюте аккаунта продавца", readonly: false, hostKey: "advert" },
  { id: "post_adv_v0_normquery_bids", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/bids", summary: "Установить ставки для поисковых кластеров", readonly: false, hostKey: "advert" },
  { id: "delete_adv_v0_normquery_bids", file: "08-promotion.yaml", method: "DELETE", path: "/adv/v0/normquery/bids", summary: "Удалить ставки поисковых кластеров", readonly: false, hostKey: "advert" },
  { id: "post_adv_v0_normquery_get_minus", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/get-minus", summary: "Список минус-фраз кампаний", readonly: true, hostKey: "advert" },
  { id: "post_adv_v0_normquery_set_minus", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/set-minus", summary: "Установка и удаление минус-фраз", readonly: false, hostKey: "advert" },
  { id: "get_adv_v1_count", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/count", summary: "Количество медиакампаний", readonly: true, hostKey: "advertMedia" },
  { id: "get_adv_v1_adverts", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/adverts", summary: "Список медиакампаний", readonly: true, hostKey: "advertMedia" },
  { id: "get_adv_v1_advert", file: "08-promotion.yaml", method: "GET", path: "/adv/v1/advert", summary: "Информация о медиакампании", readonly: true, hostKey: "advertMedia" },
  { id: "get_adv_v3_fullstats", file: "08-promotion.yaml", method: "GET", path: "/adv/v3/fullstats", summary: "Статистика кампаний", readonly: true, hostKey: "advert" },
  { id: "post_adv_v1_stats", file: "08-promotion.yaml", method: "POST", path: "/adv/v1/stats", summary: "Статистика медиакампаний", readonly: true, hostKey: "advertMedia" },
  { id: "get_api_v1_calendar_promotions", file: "08-promotion.yaml", method: "GET", path: "/api/v1/calendar/promotions", summary: "Список акций", readonly: true, hostKey: "calendar" },
  { id: "get_api_v1_calendar_promotions_details", file: "08-promotion.yaml", method: "GET", path: "/api/v1/calendar/promotions/details", summary: "Детальная информация об акциях", readonly: true, hostKey: "calendar" },
  { id: "get_api_v1_calendar_promotions_nomenclatures", file: "08-promotion.yaml", method: "GET", path: "/api/v1/calendar/promotions/nomenclatures", summary: "Список товаров для участия в акции", readonly: true, hostKey: "calendar" },
  { id: "post_api_v1_calendar_promotions_upload", file: "08-promotion.yaml", method: "POST", path: "/api/v1/calendar/promotions/upload", summary: "Добавить товар в акцию", readonly: false, hostKey: "calendar" },
  { id: "post_adv_v0_normquery_list", file: "08-promotion.yaml", method: "POST", path: "/adv/v0/normquery/list", summary: "Списки активных и неактивных поисковых кластеров", readonly: true, hostKey: "advert" },
  { id: "post_adv_v1_normquery_stats", file: "08-promotion.yaml", method: "POST", path: "/adv/v1/normquery/stats", summary: "Статистика по поисковым кластерам с детализацией по дням", readonly: true, hostKey: "advert" },
  { id: "getV1NewFeedbacksQuestions", file: "09-communications.yaml", method: "GET", path: "/api/v1/new-feedbacks-questions", summary: "Непросмотренные отзывы и вопросы", readonly: true, hostKey: "feedbacks" },
  { id: "getV1QuestionsCountUnanswered", file: "09-communications.yaml", method: "GET", path: "/api/v1/questions/count-unanswered", summary: "Неотвеченные вопросы", readonly: true, hostKey: "feedbacks" },
  { id: "getV1QuestionsCount", file: "09-communications.yaml", method: "GET", path: "/api/v1/questions/count", summary: "Количество вопросов", readonly: true, hostKey: "feedbacks" },
  { id: "getV1Questions", file: "09-communications.yaml", method: "GET", path: "/api/v1/questions", summary: "Список вопросов", readonly: true, hostKey: "feedbacks" },
  { id: "patchV1Questions", file: "09-communications.yaml", method: "PATCH", path: "/api/v1/questions", summary: "Работа с вопросами", readonly: false, hostKey: "feedbacks" },
  { id: "getV1Question", file: "09-communications.yaml", method: "GET", path: "/api/v1/question", summary: "Получить вопрос по ID", readonly: true, hostKey: "feedbacks" },
  { id: "getV1FeedbacksCountUnanswered", file: "09-communications.yaml", method: "GET", path: "/api/v1/feedbacks/count-unanswered", summary: "Необработанные отзывы", readonly: true, hostKey: "feedbacks" },
  { id: "getV1FeedbacksCount", file: "09-communications.yaml", method: "GET", path: "/api/v1/feedbacks/count", summary: "Количество отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "getV1Feedbacks", file: "09-communications.yaml", method: "GET", path: "/api/v1/feedbacks", summary: "Список отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "postV1FeedbacksAnswer", file: "09-communications.yaml", method: "POST", path: "/api/v1/feedbacks/answer", summary: "Ответить на отзыв", readonly: false, hostKey: "feedbacks" },
  { id: "patchV1FeedbacksAnswer", file: "09-communications.yaml", method: "PATCH", path: "/api/v1/feedbacks/answer", summary: "Отредактировать ответ на отзыв", readonly: false, hostKey: "feedbacks" },
  { id: "postV1FeedbacksOrderReturn", file: "09-communications.yaml", method: "POST", path: "/api/v1/feedbacks/order/return", summary: "Возврат товара по ID отзыва", readonly: false, hostKey: "feedbacks" },
  { id: "getV1Feedback", file: "09-communications.yaml", method: "GET", path: "/api/v1/feedback", summary: "Получить отзыв по ID", readonly: true, hostKey: "feedbacks" },
  { id: "getV1FeedbacksArchive", file: "09-communications.yaml", method: "GET", path: "/api/v1/feedbacks/archive", summary: "Список архивных отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "getFeedbacksV1Pins", file: "09-communications.yaml", method: "GET", path: "/api/feedbacks/v1/pins", summary: "Список закреплённых и откреплённых отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "postFeedbacksV1Pins", file: "09-communications.yaml", method: "POST", path: "/api/feedbacks/v1/pins", summary: "Закрепить отзывы", readonly: false, hostKey: "feedbacks" },
  { id: "deleteFeedbacksV1Pins", file: "09-communications.yaml", method: "DELETE", path: "/api/feedbacks/v1/pins", summary: "Открепить отзывы", readonly: false, hostKey: "feedbacks" },
  { id: "getFeedbacksV1PinsCount", file: "09-communications.yaml", method: "GET", path: "/api/feedbacks/v1/pins/count", summary: "Количество закреплённых и откреплённых отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "getFeedbacksV1PinsLimits", file: "09-communications.yaml", method: "GET", path: "/api/feedbacks/v1/pins/limits", summary: "Лимиты закреплённых отзывов", readonly: true, hostKey: "feedbacks" },
  { id: "getV1SellerChats", file: "09-communications.yaml", method: "GET", path: "/api/v1/seller/chats", summary: "Список чатов", readonly: true, hostKey: "chat" },
  { id: "getV1SellerEvents", file: "09-communications.yaml", method: "GET", path: "/api/v1/seller/events", summary: "События чатов", readonly: true, hostKey: "chat" },
  { id: "postV1SellerMessage", file: "09-communications.yaml", method: "POST", path: "/api/v1/seller/message", summary: "Отправить сообщение", readonly: false, hostKey: "chat" },
  { id: "getV1SellerDownloadId", file: "09-communications.yaml", method: "GET", path: "/api/v1/seller/download/{id}", summary: "Получить файл из сообщения", readonly: true, hostKey: "chat" },
  { id: "getV1Claims", file: "09-communications.yaml", method: "GET", path: "/api/v1/claims", summary: "Заявки покупателей на возврат", readonly: true, hostKey: "returns" },
  { id: "patchV1Claim", file: "09-communications.yaml", method: "PATCH", path: "/api/v1/claim", summary: "Ответ на заявку покупателя", readonly: false, hostKey: "returns" },
  { id: "getV1TariffsCommission", file: "10-tariffs.yaml", method: "GET", path: "/api/v1/tariffs/commission", summary: "Комиссия по категориям товаров", readonly: true, hostKey: "common" },
  { id: "getV1AcceptanceCoefficients", file: "10-tariffs.yaml", method: "GET", path: "/api/tariffs/v1/acceptance/coefficients", summary: "Тарифы на поставку", readonly: true, hostKey: "common" },
  { id: "getV1TariffsBox", file: "10-tariffs.yaml", method: "GET", path: "/api/v1/tariffs/box", summary: "Тарифы для коробов", readonly: true, hostKey: "common" },
  { id: "getV1TariffsPallet", file: "10-tariffs.yaml", method: "GET", path: "/api/v1/tariffs/pallet", summary: "Тарифы для монопаллет", readonly: true, hostKey: "common" },
  { id: "getV1TariffsReturn", file: "10-tariffs.yaml", method: "GET", path: "/api/v1/tariffs/return", summary: "Тарифы на\\_возврат", readonly: true, hostKey: "common" },
  { id: "postV3SalesFunnelProducts", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v3/sales-funnel/products", summary: "Статистика карточек товаров за период", readonly: true, hostKey: "analytics" },
  { id: "postV3SalesFunnelProductsHistory", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v3/sales-funnel/products/history", summary: "Статистика карточек товаров по дням", readonly: true, hostKey: "analytics" },
  { id: "postV3SalesFunnelGroupedHistory", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v3/sales-funnel/grouped/history", summary: "Статистика групп карточек товаров по дням", readonly: true, hostKey: "analytics" },
  { id: "postV2NmReportDownloads", file: "11-analytics.yaml", method: "POST", path: "/api/v2/nm-report/downloads", summary: "Создать отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV2NmReportDownloads", file: "11-analytics.yaml", method: "GET", path: "/api/v2/nm-report/downloads", summary: "Получить список отчётов", readonly: true, hostKey: "analytics" },
  { id: "postV2NmReportDownloadsRetry", file: "11-analytics.yaml", method: "POST", path: "/api/v2/nm-report/downloads/retry", summary: "Сгенерировать отчёт повторно", readonly: true, hostKey: "analytics" },
  { id: "getV2NmReportDownloadsFileDownloadId", file: "11-analytics.yaml", method: "GET", path: "/api/v2/nm-report/downloads/file/{downloadId}", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "postV2SearchReportReport", file: "11-analytics.yaml", method: "POST", path: "/api/v2/search-report/report", summary: "Основная страница", readonly: true, hostKey: "analytics" },
  { id: "postV2SearchReportTableGroups", file: "11-analytics.yaml", method: "POST", path: "/api/v2/search-report/table/groups", summary: "Пагинация по группам", readonly: true, hostKey: "analytics" },
  { id: "postV2SearchReportTableDetails", file: "11-analytics.yaml", method: "POST", path: "/api/v2/search-report/table/details", summary: "Пагинация по товарам в группе", readonly: true, hostKey: "analytics" },
  { id: "postV2SearchReportProductSearchTexts", file: "11-analytics.yaml", method: "POST", path: "/api/v2/search-report/product/search-texts", summary: "Поисковые запросы по товару", readonly: true, hostKey: "analytics" },
  { id: "postV2SearchReportProductOrders", file: "11-analytics.yaml", method: "POST", path: "/api/v2/search-report/product/orders", summary: "Заказы и позиции по поисковым запросам товара", readonly: true, hostKey: "analytics" },
  { id: "postV1StocksReportWbWarehouses", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v1/stocks-report/wb-warehouses", summary: "Остатки на складах WB", readonly: true, hostKey: "analytics" },
  { id: "postV2StocksReportProductsGroups", file: "11-analytics.yaml", method: "POST", path: "/api/v2/stocks-report/products/groups", summary: "Данные по группам", readonly: true, hostKey: "analytics" },
  { id: "postV2StocksReportProductsProducts", file: "11-analytics.yaml", method: "POST", path: "/api/v2/stocks-report/products/products", summary: "Данные по товарам", readonly: true, hostKey: "analytics" },
  { id: "postV2StocksReportProductsSizes", file: "11-analytics.yaml", method: "POST", path: "/api/v2/stocks-report/products/sizes", summary: "Данные по размерам", readonly: true, hostKey: "analytics" },
  { id: "postV2StocksReportOffices", file: "11-analytics.yaml", method: "POST", path: "/api/v2/stocks-report/offices", summary: "Данные по складам", readonly: true, hostKey: "analytics" },
  { id: "postV2ItemRating", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v2/item-rating", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "postV1ItemRating", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v1/item-rating", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "postV1OrderFeed", file: "11-analytics.yaml", method: "POST", path: "/api/analytics/v1/order-feed", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1SupplierOrders", file: "12-reports.yaml", method: "GET", path: "/api/v1/supplier/orders", summary: "Заказы", readonly: true, hostKey: "statistics" },
  { id: "getV1SupplierSales", file: "12-reports.yaml", method: "GET", path: "/api/v1/supplier/sales", summary: "Продажи", readonly: true, hostKey: "statistics" },
  { id: "postV1AnalyticsExciseReport", file: "12-reports.yaml", method: "POST", path: "/api/v1/analytics/excise-report", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1WarehouseRemains", file: "12-reports.yaml", method: "GET", path: "/api/v1/warehouse_remains", summary: "Создать отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1WarehouseRemainsTasksTaskIdStatus", file: "12-reports.yaml", method: "GET", path: "/api/v1/warehouse_remains/tasks/{task_id}/status", summary: "Проверить статус", readonly: true, hostKey: "analytics" },
  { id: "getV1WarehouseRemainsTasksTaskIdDownload", file: "12-reports.yaml", method: "GET", path: "/api/v1/warehouse_remains/tasks/{task_id}/download", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1MeasurementPenalties", file: "12-reports.yaml", method: "GET", path: "/api/analytics/v1/measurement-penalties", summary: "Удержания за занижение габаритов упаковки", readonly: true, hostKey: "analytics" },
  { id: "getV1WarehouseMeasurements", file: "12-reports.yaml", method: "GET", path: "/api/analytics/v1/warehouse-measurements", summary: "Замеры склада", readonly: true, hostKey: "analytics" },
  { id: "getV1Deductions", file: "12-reports.yaml", method: "GET", path: "/api/analytics/v1/deductions", summary: "Подмены и неверные вложения", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsAntifraudDetails", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/antifraud-details", summary: "Самовыкупы", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsGoodsLabeling", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/goods-labeling", summary: "Маркировка товара", readonly: true, hostKey: "analytics" },
  { id: "getV1AcceptanceReport", file: "12-reports.yaml", method: "GET", path: "/api/v1/acceptance_report", summary: "Создать отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AcceptanceReportTasksTaskIdStatus", file: "12-reports.yaml", method: "GET", path: "/api/v1/acceptance_report/tasks/{task_id}/status", summary: "Проверить статус", readonly: true, hostKey: "analytics" },
  { id: "getV1AcceptanceReportTasksTaskIdDownload", file: "12-reports.yaml", method: "GET", path: "/api/v1/acceptance_report/tasks/{task_id}/download", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1PaidStorage", file: "12-reports.yaml", method: "GET", path: "/api/v1/paid_storage", summary: "Создать отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1PaidStorageTasksTaskIdStatus", file: "12-reports.yaml", method: "GET", path: "/api/v1/paid_storage/tasks/{task_id}/status", summary: "Проверить статус", readonly: true, hostKey: "analytics" },
  { id: "getV1PaidStorageTasksTaskIdDownload", file: "12-reports.yaml", method: "GET", path: "/api/v1/paid_storage/tasks/{task_id}/download", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsRegionSale", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/region-sale", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsBrandShareBrands", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/brand-share/brands", summary: "Бренды продавца", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsBrandShareParentSubjects", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/brand-share/parent-subjects", summary: "Родительские категории бренда", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsBrandShare", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/brand-share", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsBannedProducsBlocked", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/banned-products/blocked", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsBannedProductsShadowed", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/banned-products/shadowed", summary: "Скрытые из каталога", readonly: true, hostKey: "analytics" },
  { id: "getV1AnalyticsGoodsReturn", file: "12-reports.yaml", method: "GET", path: "/api/v1/analytics/goods-return", summary: "Получить отчёт", readonly: true, hostKey: "analytics" },
  { id: "getV1AccountBalance", file: "13-finances.yaml", method: "GET", path: "/api/v1/account/balance", summary: "Получить баланс продавца", readonly: true, hostKey: "finance" },
  { id: "postV1SalesReportsList", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/sales-reports/list", summary: "Список отчётов реализации", readonly: true, hostKey: "finance" },
  { id: "postV1SalesReportsDetailedReportId", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/sales-reports/detailed/{reportId}", summary: "Детализации к отчётам реализации по ID отчётов", readonly: true, hostKey: "finance" },
  { id: "postV1SalesReportsDetailed", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/sales-reports/detailed", summary: "Детализации к отчётам реализации за период", readonly: true, hostKey: "finance" },
  { id: "postV1AcquiringList", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/acquiring/list", summary: "Список отчётов об издержках на приём платежей", readonly: true, hostKey: "finance" },
  { id: "postV1AcquiringDetailedReportId", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/acquiring/detailed/{reportId}", summary: "Детализации к отчётам об издержках на приём платежей по ID отчётов", readonly: true, hostKey: "finance" },
  { id: "postV1AcquiringDetailed", file: "13-finances.yaml", method: "POST", path: "/api/finance/v1/acquiring/detailed", summary: "Детализации к отчётам об издержках на приём платежей за период", readonly: true, hostKey: "finance" },
  { id: "getV1DocumentsCategories", file: "13-finances.yaml", method: "GET", path: "/api/v1/documents/categories", summary: "Категории документов", readonly: true, hostKey: "documents" },
  { id: "getV1DocumentsList", file: "13-finances.yaml", method: "GET", path: "/api/v1/documents/list", summary: "Список документов", readonly: true, hostKey: "documents" },
  { id: "getV1DocumentsDownload", file: "13-finances.yaml", method: "GET", path: "/api/v1/documents/download", summary: "Получить документ", readonly: true, hostKey: "documents" },
  { id: "postV1DocumentsDownloadAll", file: "13-finances.yaml", method: "POST", path: "/api/v1/documents/download/all", summary: "Получить документы", readonly: true, hostKey: "documents" },
  { id: "LoadKeys", file: "14-wbd.yaml", method: "POST", path: "/api/v1/keys-api/keys", summary: "Добавить ключи активации", readonly: false, hostKey: "digital" },
  { id: "DeleteKeysByIDs", file: "14-wbd.yaml", method: "DELETE", path: "/api/v1/keys-api/keys", summary: "Удалить ключи активации", readonly: false, hostKey: "digital" },
  { id: "GetRedeemedKeys", file: "14-wbd.yaml", method: "GET", path: "/api/v1/keys-api/keys/redeemed", summary: "Получить купленные ключи", readonly: true, hostKey: "digital" },
  { id: "offerKeysCountGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/offer/keys/{offer_id}", summary: "Получить количество ключей для предложения", readonly: true, hostKey: "digital" },
  { id: "offerKeysGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/offer/keys/{offer_id}/list", summary: "Получить список ключей", readonly: true, hostKey: "digital" },
  { id: "offerCreate", file: "14-wbd.yaml", method: "POST", path: "/api/v1/offers", summary: "Создать новое предложение", readonly: false, hostKey: "digital" },
  { id: "offersUploadThumbnail", file: "14-wbd.yaml", method: "POST", path: "/api/v1/offers/thumb", summary: "Добавить или обновить обложку предложения", readonly: false, hostKey: "digital" },
  { id: "offerUpdate", file: "14-wbd.yaml", method: "POST", path: "/api/v1/offers/{offer_id}", summary: "Редактировать предложение", readonly: false, hostKey: "digital" },
  { id: "offerGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/offers/{offer_id}", summary: "Получить информацию о предложении", readonly: true, hostKey: "digital" },
  { id: "offersAuthorGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/offers/author", summary: "Получить список своих предложений", readonly: true, hostKey: "digital" },
  { id: "offerUpdatePrice", file: "14-wbd.yaml", method: "POST", path: "/api/v1/offer/price/{offer_id}", summary: "Обновить цену", readonly: false, hostKey: "digital" },
  { id: "offerUpdateStatus", file: "14-wbd.yaml", method: "POST", path: "/api/v1/offer/{offer_id}", summary: "Обновить статус", readonly: false, hostKey: "digital" },
  { id: "GetCatalog", file: "14-wbd.yaml", method: "GET", path: "/api/v1/catalog", summary: "Получить категории и их подкатегории", readonly: true, hostKey: "digital" },
  { id: "contentUploadIllustration", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/illustration", summary: "Загрузить обложку контента", readonly: false, hostKey: "digital" },
  { id: "contentUploadInit", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/upload/init", summary: "Инициализировать новый контент", readonly: false, hostKey: "digital" },
  { id: "contentUploadChunk", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/upload/chunk", summary: "Загрузить контент (файл)", readonly: false, hostKey: "digital" },
  { id: "contentUpdate", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/author/{content_id}", summary: "Редактировать контент", readonly: false, hostKey: "digital" },
  { id: "contentIdGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/content/author/{content_id}", summary: "Получить информацию о контенте", readonly: true, hostKey: "digital" },
  { id: "contentAuthorGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/content/author", summary: "Получить список своего контента", readonly: true, hostKey: "digital" },
  { id: "contentDownloadGet", file: "14-wbd.yaml", method: "GET", path: "/api/v1/content/download/{uri}", summary: "Скачать контент", readonly: true, hostKey: "digital" },
  { id: "contentDelete", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/delete", summary: "Удалить контент", readonly: false, hostKey: "digital" },
  { id: "contentGallery", file: "14-wbd.yaml", method: "POST", path: "/api/v1/content/gallery", summary: "Загрузить медиафайлы для предложения", readonly: false, hostKey: "digital" },
];

export function resolveHost(hostKey: string): string {
  const h = (WB_HOSTS as Record<string, string>)[hostKey];
  if (!h) throw new Error(`unknown hostKey ${hostKey}`);
  return h;
}

export function fillPath(path: string, params: Record<string, string | number> = {}): string {
  return path.replace(/\{([^}]+)\}/g, (_, k) => {
    if (params[k] === undefined || params[k] === null) {
      throw new Error(`missing path param ${k} for ${path}`);
    }
    return encodeURIComponent(String(params[k]));
  });
}

async function rawFetch(
  token: string,
  method: string,
  url: string,
  body?: unknown,
): Promise<WbHttpResult> {
  try {
    const res = await fetch(url, {
      method,
      headers: {
        Authorization: token,
        Accept: 'application/json',
        ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}),
      },
      body: body !== undefined ? JSON.stringify(body) : undefined,
      signal: AbortSignal.timeout(45000),
    });
    const text = await res.text();
    let data: unknown = {};
    try { data = text ? JSON.parse(text) : {}; } catch { data = { raw: text.slice(0, 500) }; }
    const err = !res.ok
      ? String((data as Record<string, unknown>)?.detail || (data as Record<string, unknown>)?.title || (data as Record<string, unknown>)?.errorText || `HTTP ${res.status}`).slice(0, 400)
      : '';
    return { ok: res.ok, status: res.status, data, errorText: err };
  } catch (e) {
    return { ok: false, status: 0, data: {}, errorText: String(e).slice(0, 300) };
  }
}

/** Вызов любого эндпоинта из реестра по id. */
export async function callWbEndpoint(
  token: string,
  endpointId: string,
  opts: { pathParams?: Record<string, string | number>; query?: Record<string, string | number | boolean>; body?: unknown } = {},
): Promise<WbHttpResult & { endpointId: string }> {
  const ep = WB_OPENAPI_ENDPOINTS.find((e) => e.id === endpointId);
  if (!ep) return { ok: false, status: 0, data: {}, errorText: `unknown endpoint ${endpointId}`, endpointId };
  let path = fillPath(ep.path, opts.pathParams || {});
  if (opts.query && Object.keys(opts.query).length) {
    const q = new URLSearchParams();
    for (const [k, v] of Object.entries(opts.query)) q.set(k, String(v));
    path += (path.includes('?') ? '&' : '?') + q.toString();
  }
  const url = `${resolveHost(ep.hostKey)}${path}`;
  const r = await rawFetch(token, ep.method, url, opts.body);
  return { ...r, endpointId };
}

export function listEndpointsByFile(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const e of WB_OPENAPI_ENDPOINTS) out[e.file] = (out[e.file] || 0) + 1;
  return out;
}
